Adding Julia language
devstrons/heloworld.xyz pull request #93
Opened 2021-12-15 06:14 UTC by Shivansh-yadav13

### **Description**

Added the Julia language to the list.

This PR fixes #83 

**Notes for Reviewers:**

**[Signed commits](https://github.com/devstrons/hello-world/blob/master/CONTRIBUTING.md)**

- [x] Yes, I am a Member of **DEVSTRONS'**

**Discord ID** - **Shivansh Yadav#6952**

2021-12-15 19:34 UTC, Panquesito7 requested changes
Great work! 🚀

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +
```suggestion
lang: Julia
syntax: julia
title: Julia is a high-level, high-performance, dynamic programming language.
author: Shivansh Yadav
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### What is Julia
```suggestion
## 🤔 What is Julia
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### Why to use Julia
```suggestion
## 📈 Why to use Julia
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +- Dynamic and composable
```suggestion
- When using Python and other languages in production and environments it becomes a sort of a burden and a limitation. While Julia is computationally efficient and easy to use for developers.

- Syntactically Julia is quite similar to python so if you write code that does very similar stuff to what it does in python, it does faster in Julia.

- You can also embed all Python, C/C++, and Java code directly inside Julia, run that code and interact with output using Julia.

**In Short**

- Open-source
- Interoperability
- Reproducible
- Build to be fast
- Well suited for data-intensive problems
- Familiar Syntax
- Dynamic and composable
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### Setting up Julia development environment
```suggestion
## 🛠️ Setting up Julia development environment
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +#### On Windows & Mac
```suggestion
### 💻 On Windows & Mac
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +##### Step 1:
```suggestion
#### Step 1
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +- Download Julia from [here.](https://julialang.org/downloads/)
```suggestion
- Download Julia from the official [Julia website](https://julialang.org/downloads/).
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +##### Step 2:
```suggestion
#### Step 2
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +- Create an example file index.jl and start using Julia.
```suggestion
- Create an example file `index.jl` and start using Julia.
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +#### On Linux
```suggestion
### 🐧 On Linux
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +```
```suggestion
```bash
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +```
```suggestion
```bash
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +```
```suggestion
```bash
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +```
```suggestion
```bash
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### Popular Julia IDEs/Editors
```suggestion
## ✏️ Popular Julia IDEs/Editors
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### Some cool projects in Julia
```suggestion
## 😎 Some cool projects in Julia
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +### Conclusion
```suggestion
## 🚀 Conclusion
```

2021-12-15 19:34 UTC, Panquesito7 commented on lang/Julia.md
> +If you are someone who is very interested in the climate space or the medical space then you should go for Julia.
```suggestion
If you are someone who is very interested in the climate space or the medical space then you should go for Julia.

**Thanks for reading** ✨
```

2021-12-16 03:39 UTC, Shivansh-yadav13 commented
> Great work! 🚀

Thank you!

2021-12-16 04:47 UTC, Panquesito7 commented on lang/Julia.md
> +Julia is a new, general purpose, high performance programming language with the tagline **"Looks like Python, feels like Lisp, runs like Fortran”** It is easy to   use, powerful and extremally perfor
```suggestion
Julia is a new, general-purpose, high-performance programming language with the tagline **"Looks like Python, feels like Lisp, runs like Fortran”**. It is easy to use, powerful, and extremely performant.
```

2021-12-16 16:56 UTC, Panquesito7 commented on lang/Julia.md
> +- Syntactically Julia is quite similar to python so if you write code that does very similar stuff to what it does in python, it does faster in Julia.
```suggestion
- Syntactically Julia is quite similar to Python, so if you write code that does very similar stuff to what it does in Python, it does faster in Julia.
```

2021-12-17 04:23 UTC, Panquesito7 approved these changes
For me, this is looking good 🚀 Thank you! 😄👍
CC: @amino19. Review when you have time. 🙂

2021-12-29 08:08 UTC, amino19 approved these changes
@Shivansh-yadav13: Thanks for your valuable contributions.
Apologize for the delay, we're involved on [bugtrons](https://github.com/bugtrons). :sparkles: 

@Panquesito7: Thank you so much for reviewing PR, & active participation in such practice, I  appreciate it!

2021-12-29 08:10 UTC, merged